spring:
  application:
    name: sparktech-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sparktech21/environment-variable-repo.git
        default-label: main  

server:
  port: ${port:8888}    
